### ISSUE TITLE
Upgrade to `@prenda/spark@v1.0.0-alpha.4` caused issue with `Select`

### ISSUE THREAD

**Issue by shadoath** [prenda-school/design-system#393]
Ran into an issue where using the <Select>  from Spark caused errors but once I started using <Unstable_Select>  it worked fine.

**Comment by shadoath** [comment]
Browser console error:

```
defaults.js?36ff:6 Uncaught TypeError: Cannot read properties of undefined (reading 'createElement')
    at IconComponent (defaults.js?36ff:6:1)
    at renderWithHooks (react-dom.development.js?ac89:14985:1)
    at mountIndeterminateComponent (react-dom.development.js?ac89:17811:1)
    at beginWork (react-dom.development.js?ac89:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js?ac89:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?ac89:3994:1)
    at invokeGuardedCallback (react-dom.development.js?ac89:4056:1)
    at beginWork$1 (react-dom.development.js?ac89:23964:1)
    at performUnitOfWork (react-dom.development.js?ac89:22776:1)
    at workLoopSync (react-dom.development.js?ac89:22707:1)
    at renderRootSync (react-dom.development.js?ac89:22670:1)
    at performSyncWorkOnRoot (react-dom.development.js?ac89:22293:1)
    at eval (react-dom.development.js?ac89:11327:1)
    at unstable_runWithPriority (scheduler.development.js?bcd2:468:1)
    at runWithPriority$1 (react-dom.development.js?ac89:11276:1)
    at flushSyncCallbackQueueImpl (react-dom.development.js?ac89:11322:1)
    at flushSyncCallbackQueue (react-dom.development.js?ac89:11309:1)
    at flushSync (react-dom.development.js?ac89:22467:1)
    at scheduleRefresh (react-dom.development.js?ac89:24429:1)
    at Object.renderer.scheduleRefresh (react_devtools_backend.js:6413:16)
    at eval (react-refresh-runtime.development.js?7e84:265:1)
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js?7e84:254:1)
    at eval (helpers.js?7e26:125:1)
IconComponent @ defaults.js?36ff:6
renderWithHooks @ react-dom.development.js?ac89:14985
mountIndeterminateComponent @ react-dom.development.js?ac89:17811
beginWork @ react-dom.development.js?ac89:19049
callCallback @ react-dom.development.js?ac89:3945
invokeGuardedCallbackDev @ react-dom.development.js?ac89:3994
invokeGuardedCallback @ react-dom.development.js?ac89:4056
beginWork$1 @ react-dom.development.js?ac89:23964
performUnitOfWork @ react-dom.development.js?ac89:22776
workLoopSync @ react-dom.development.js?ac89:22707
renderRootSync @ react-dom.development.js?ac89:22670
performSyncWorkOnRoot @ react-dom.development.js?ac89:22293
eval @ react-dom.development.js?ac89:11327
unstable_runWithPriority @ scheduler.development.js?bcd2:468
runWithPriority$1 @ react-dom.development.js?ac89:11276
flushSyncCallbackQueueImpl @ react-dom.development.js?ac89:11322
flushSyncCallbackQueue @ react-dom.development.js?ac89:11309
flushSync @ react-dom.development.js?ac89:22467
scheduleRefresh @ react-dom.development.js?ac89:24429
renderer.scheduleRefresh @ react_devtools_backend.js:6413
eval @ react-refresh-runtime.development.js?7e84:265
performReactRefresh @ react-refresh-runtime.development.js?7e84:254
eval @ helpers.js?7e26:125
setTimeout (async)
scheduleUpdate @ helpers.js?7e26:120
eval @ form.tsx?887e:36
eval @ form.tsx?887e:36
./components/students/form.tsx @ update.1c826219664fd6a0.hot-update.js:18
options.factory @ webpack.js?ts=1650897620125:618
__webpack_require__ @ webpack.js?ts=1650897620125:37
_requireSelf @ webpack.js?ts=1650897620125:327
apply @ webpack.js?ts=1650897620125:1047
(anonymous) @ webpack.js?ts=1650897620125:555
internalApply @ webpack.js?ts=1650897620125:553
(anonymous) @ webpack.js?ts=1650897620125:494
waitForBlockingPromises @ webpack.js?ts=1650897620125:447
(anonymous) @ webpack.js?ts=1650897620125:492
Promise.then (async)
(anonymous) @ webpack.js?ts=1650897620125:491
Promise.then (async)
(anonymous) @ webpack.js?ts=1650897620125:470
Promise.then (async)
hotCheck @ webpack.js?ts=1650897620125:461
tryApplyUpdates @ hot-dev-client.js?1600:251
handleSuccess @ hot-dev-client.js?1600:63
processMessage @ hot-dev-client.js?1600:173
eval @ hot-dev-client.js?1600:15
eval @ websocket.js?a9be:57
handleMessage @ websocket.js?a9be:56
next-dev.js?3515:25 The above error occurred in the <IconComponent> component:

    at IconComponent (webpack-internal:///./node_modules/@prenda/spark/esm/Select/defaults.js:13:31)
    at SelectInput (webpack-internal:///./node_modules/@material-ui/core/esm/Select/SelectInput.js:54:24)
    at div
    at InputBase (webpack-internal:///./node_modules/@material-ui/core/esm/InputBase/InputBase.js:214:30)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Input (webpack-internal:///./node_modules/@material-ui/core/esm/Input/Input.js:130:32)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Select (webpack-internal:///./node_modules/@material-ui/core/esm/Select/Select.js:44:32)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at FormControl (webpack-internal:///./node_modules/@material-ui/core/esm/FormControl/FormControl.js:84:24)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at StyledComponent (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/styled/styled.js:95:28)
    at div
    at Grid (webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:236:35)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at Grid (webpack-internal:///./node_modules/@material-ui/core/esm/Grid/Grid.js:236:35)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at div
    at Paper (webpack-internal:///./node_modules/@material-ui/core/esm/Paper/Paper.js:48:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at Card (webpack-internal:///./node_modules/@material-ui/core/esm/Card/Card.js:28:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at StudentForm (webpack-internal:///./components/students/form.tsx:125:26)
    at div
    at Container (webpack-internal:///./node_modules/@material-ui/core/esm/Container/Container.js:85:23)
    at WithStyles (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/withStyles/withStyles.js:61:31)
    at UpdateStudent (webpack-internal:///./pages/students/[studentId]/update.tsx:68:72)
    at Auth (webpack-internal:///./pages/_app.tsx:257:26)
    at main
    at div
    at eval (webpack-internal:///./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:57:66)
    at MainNav (webpack-internal:///./components/nav/index.tsx:121:91)
    at EnrollmentContextProvider (webpack-internal:///./contexts/EnrollmentContext.tsx:168:27)
    at UserContextProvider (webpack-internal:///./contexts/UserContext.tsx:31:26)
    at SessionProvider (webpack-internal:///./node_modules/next-auth/react/index.js:417:24)
    at AlertProvider (webpack-internal:///./contexts/AlertContext.tsx:56:27)
    at ThemeProvider (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:42:24)
    at StylesProvider (webpack-internal:///./node_modules/@material-ui/core/node_modules/@material-ui/styles/esm/StylesProvider/StylesProvider.js:50:24)
    at SparkThemeProvider (webpack-internal:///./node_modules/@prenda/spark/esm/SparkThemeProvider/SparkThemeProvider.js:21:12)
    at MyApp (webpack-internal:///./pages/_app.tsx:114:27)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20638)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23179)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:323:9)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:820:26)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:944:27)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by shadoath** [comment]
Relevant code: 

```
<Select
  required
  value={student.grade === null ? "" : student.grade}
  onChange={(e) => {
    setStudent({ grade: e.target.value as number })
  }}
  style={{ margin: 0 }}
>
  <MenuItem disabled value="">
    Select grade
  </MenuItem>
  {Object.entries(STUDENT_GRADES).map(([grade, value]) => (
    <MenuItem key={grade} value={value}>
      {grade} {value !== 0 && "grade"}
    </MenuItem>
  ))}
</Select>
```

**Comment by WilliamKelley** [comment]
Ah, this error happens when a JSX file using JSX syntax doesn't have "react" in scope. I believe the fix is adding `import React from 'react';` to [`libs/spark/src/Select/defaults.tsx`](https://github.com/prenda-school/design-system/blob/main/libs/spark/src/Select/defaults.tsx).

Will create PR for fix.
